name: Cypress Smoke and Regression Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  cypress-run-smoke:
    name: Smoke Suite
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
      CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress_run_smoke_tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy-run-ui-smoke-chrome

    #uploads the test results under cypress/reports folder
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-report-chrome-smoke
          path: cypress/reports/html 
          retention-days: 7


# ------------------------- Regression --------------------------

  cypress-run-regression:
    name: Regression Suite
    runs-on: ubuntu-latest
    needs: cypress-run-smoke                     # ➜ runs only if smoke succeeded
    timeout-minutes: 30

    env:
      CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
      CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Run regression tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy-run-ui-regression-chrome     # <-- your script

      - name: Upload Regression Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-regression
          path: cypress/reports/html
          retention-days: 14

# ------------------------- API tests smoke --------------------------
  cypress-run-api-smoke:
    name: Smoke API Suite
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress_run_api_smoke_tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy-run-api-smoke

  # ------------------------- API tests regression ----------------------------

  cypress-run-api-regression:
    name: Regression Suite
    runs-on: ubuntu-latest
    needs: cypress-run-api-smoke                     # ➜ runs only if smoke succeeded
    timeout-minutes: 30

    env:
      CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Run regression tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy-run-api-regression     # <-- your script

